export const userData = [
  {
    _id: 0,
    firstName: "Simon",
    lastName: "Lau",
    organisation: "General Assembly Hungry",
    contactNum: "99998888",
    email: "simonlau@ga.com",
    username: "simonlau",
    type: 0,
    contributeList: [],
    myCart: [],
    receivedList: [],
    createdAt: 1029301932010,
    imgFile: "",
    status: 1,
  },
  {
    _id: 1,
    firstName: "Nausheen",
    lastName: ":)",
    organisation: "",
    contactNum: "88887777",
    email: "nausheen@ga.com",
    username: "nausheen",
    type: 1,
    contributeList: [],
    myCart: [],
    receivedList: ["123", "456"],
    createdAt: 1012313452,
    imgFile: "",
    status: 1,
  },
  {
    _id: 2,
    firstName: "Mitch",
    lastName: "Goon",
    organisation: "",
    contactNum: "77776666",
    email: "mitchg@heavymetal.com",
    username: "mitchg",
    type: 0,
    contributeList: [],
    myCart: [],
    receivedList: ["0", "1"],
    createdAt: 1000333421,
    imgFile: "",
    status: 1,
  },
  {
    _id: 3,
    firstName: "Renice",
    lastName: "Goh",
    organisation: "Save the Hangries",
    contactNum: "66665555",
    email: "reniceg@coding.com",
    username: "reniceg",
    type: 0,
    contributeList: [],
    myCart: [],
    receivedList: ["987", "654", "321"],
    createdAt: 1004444444,
    imgFile: "",
    status: 1,
  }
];

export const batchData = [
    {
        _id: 0,
        createdAt: 112039485.
        listingsCollection: [0, 1],
        contactPerson: "Gloria",
        contactNum: 98765432,
        collectionAdress: 513456,
        status: 1
    },
    {
        _id: 1,
        createdAt: 112039486,
        listingsCollection: [2, 3],
        contactPerson: "Bairong",
        contactNum: 91234567,
        collectionAdress: 123456,
        status: 1
    },
]

export const listingData = [
    {
        _id: 0,
        title: "apple",
        quantity: "5",
        category: "fruit",
        isHalal: true,
        isVegetarian: true,
        description: "bright red pretty shinny fat round",
        bestBefore: "04/5/1960",
        image: "",
        status: 2,
        recipient: 2,
        Contributor: 1
    },
    {
        _id: 1,
        title: "pear",
        quantity: "5",
        category: "fruit",
        isHalal: true,
        isVegetarian: true,
        description: "bright green pretty shinny skinny shapy",
        bestBefore: "03/05/1955",
        image: "",
        status: 1,
        recipient: null,
        Contributor: 0
    },
    {
        _id: 2,
        title: "durian",
        quantity: "5",
        category: "fruit",
        isHalal: true,
        isVegetarian: true,
        description: "dull spikey painful hard smelly",
        bestBefore: "01/5/1990",
        image: "",
        status: 3,
        recipient: null,
        Contributor: 3
    }
]
